datastore:
  connection_string: postgresql://service:KOglU-hGiAmFs30dNg_XWg@free-tier7.aws-eu-west-1.cockroachlabs.cloud:26257/auth?sslmode=verify-full&options=--cluster%3Dsf90-cluster-2393

handler:
  jwt_signing_key: jwtsigningkeytemplate