name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env: 
  DB_STRING: postgresql://service:${{ secrets.DB_KEY }}@free-tier7.aws-eu-west-1.cockroachlabs.cloud:26257/auth?sslmode=verify-full&options=--cluster%3Dsf90-cluster-2393

jobs:

  login:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: sf90registry
        password: ${{ secrets.REGISTRY_KEY }}
        login-server: sf90registry.azurecr.io

        

    - uses: actions/checkout@v3
    - name: Prune images
      run: >
        docker image prune -a --force
      


    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile --tag auth:latest --build-arg auth_token=${{ secrets.AUTH_TOKEN }} && docker tag auth:latest sf90registry.azurecr.io/services/auth && docker push sf90registry.azurecr.io/services/auth 

    
